application: traindeathtoll
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: render_page.app
      
- url: /index\.html
  script: render_page.app
      
- url: /read_tweets
  script: read_tweets.app
  login: admin

- url: /process_tweets
  script: process_tweets.app
  login: admin

- url: /make_word_cloud
  script: make_word_cloud.app
  login: admin

- url: /.*
  script: not_found.app

libraries:
- name: ssl
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"
- name: PIL
  version: "1.1.7"

